### model
# model_name_or_path: weights/SpatialLM1.2-Qwen-0.5B-G1280
# model_name_or_path: manycore-research/SpatialLM1.1-Qwen-0.5B
model_name_or_path: work_dirs/pretrain/spatiallm1.2-0.5b-g1280-pretrain-stru3d-e50/checkpoint-24500
trust_remote_code: true

### method
do_train: true
freeze_language_tower: false
freeze_point_tower: false
train_proj_only: false

### dataset
dataset: HC3D_train # HC3D_train,HC3D_test
dataset_dir: data/HC3D/20251110-dev # HC3D-spatiallm
template: spatiallm_qwen # spatiallm_qwen, spatiallm_llama
num_bins: 1600
do_augmentation: false
random_rotation: true
random_scale: true
# replace_prompt_with_type: "arch" # "all", "arch" or "object"
cutoff_len: 8192 
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 8
save_dir: data/HC3D/20251110-dev/HC3D-g1600

### output
output_dir: work_dirs/hc3d_sft/spatiallm1.2-0.5b-g1600-sft-hc3d-e500
logging_steps: 10
save_steps: 500
overwrite_output_dir: false
save_total_limit: 2

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4 # to be more aggressive: try to change the learning rate to 5.0e-5 or 1.0e-4
adam_beta1: 0.9
adam_beta2: 0.99
adam_epsilon: 1.0e-8
num_train_epochs: 500 # total training epochs
lr_scheduler_type: cosine
warmup_ratio: 0.03
pure_bf16: true
bf16: true
fp16: false
tf32: false
ddp_timeout: 180000000
report_to: tensorboard # choices: [none, wandb, tensorboard, swanlab]
max_new_tokens: 4096

### eval
eval_dataset: HC3D_val
# val_size: 0.0001 # 验证集相对所使用的训练数据集的大小。取值在 [0,1) 之间。
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200

#
gradient_checkpointing: true
flash_attn: fa2
optim: adamw_torch_fused

disable_tqdm: false
include_num_input_tokens_seen: false 