### model
model_name_or_path: manycore-research/SpatialLM1.1-Qwen-0.5B
trust_remote_code: true

### method
do_train: true
freeze_language_tower: false
freeze_point_tower: false
train_proj_only: false

### dataset
dataset: structured3d_train,structured3d_test # structured3d_train,structured3d_test
dataset_dir: data/structured3d-spatiallm # structured3d-spatiallm
template: spatiallm_qwen # spatiallm_qwen, spatiallm_llama
num_bins: 640
do_augmentation: false
random_rotation: true
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 8
save_dir: saves/structured3d

### output
output_dir: saves
logging_steps: 10
save_steps: 500
overwrite_output_dir: false
save_total_limit: 5

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-4 # to be more aggressive: try to change the learning rate to 5.0e-5 or 1.0e-4
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0.03
pure_bf16: false
bf16: false
fp16: false
tf32: true
ddp_timeout: 180000000
report_to: wandb # choices: [none, wandb, tensorboard, swanlab]
max_new_tokens: 4096

### eval
val_size: 0.0001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
