### model
# model_name_or_path: ysmao/SpatialLM1.1-Qwen-0.5B-Structured3D-SFT
model_name_or_path: manycore-research/SpatialLM1.1-Qwen-0.5B
trust_remote_code: true

### method
do_train: true
freeze_language_tower: false
freeze_point_tower: false
train_proj_only: false

### dataset
dataset: structured3d_train # structured3d_train,structured3d_test
dataset_dir: data/structured3d-spatiallm-pzhang # structured3d-spatiallm
template: spatiallm_qwen # spatiallm_qwen, spatiallm_llama
num_bins: 640
do_augmentation: false
random_rotation: false
cutoff_len: 8192 # 输入的最大token数，超过会被截断
overwrite_cache: true # 覆盖缓存的训练和评估数据集
preprocessing_num_workers: 8
dataloader_num_workers: 8
save_dir: saves/structured3d-pzhang-g640

### output
output_dir: saves/spatiallm-0.5b-s3d-pzhang-sft-e50
logging_steps: 10
save_steps: 500
overwrite_output_dir: false
save_total_limit: 2

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4 # to be more aggressive: try to change the learning rate to 5.0e-5 or 1.0e-4
adam_beta1: 0.9
adam_beta2: 0.99
adam_epsilon: 1.0e-8
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0.03
pure_bf16: false
bf16: false
fp16: false
tf32: true
ddp_timeout: 180000000
report_to: tensorboard # choices: [none, wandb, tensorboard, swanlab]
max_new_tokens: 4096

### eval
# eval_dataset: structured3d_test
val_size: 0.001 # 验证集相对所使用的训练数据集的大小。取值在 [0,1) 之间。
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
